# Generated by Django 4.2.7 on 2023-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel_usu',
            field=models.CharField(max_length=20),
        ),
    ]
