# Generated by Django 4.2.7 on 2023-11-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planxcobertura',
            name='id_plan',
            field=models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.PROTECT, to='DentCorpApp.planes'),
        ),
    ]
