# Generated by Django 4.2.7 on 2023-11-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionesconsultorio',
            options={'verbose_name_plural': 'Asignación de Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='cajas',
            options={'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='coberturas',
            options={'verbose_name_plural': 'Coberturas'},
        ),
        migrations.AlterModelOptions(
            name='consultorios',
            options={'verbose_name_plural': 'Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='especxusuario',
            options={'verbose_name_plural': 'Especialidades por Usuario'},
        ),
        migrations.AlterModelOptions(
            name='facturasodontologicas',
            options={'verbose_name_plural': 'Facturas Odontológicas'},
        ),
        migrations.AlterModelOptions(
            name='facturasservext',
            options={'verbose_name_plural': 'Facturas de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='pagosservext',
            options={'verbose_name_plural': 'Pagos de servicios'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='planxcobertura',
            options={'verbose_name_plural': 'Planes x Coberturas'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='serviciosodontologicos',
            options={'verbose_name_plural': 'Servicios Odontológicos'},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
