# Generated by Django 4.2.7 on 2023-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ape_usu',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom_usu',
        ),
    ]
