# Generated by Django 4.2.7 on 2023-11-15 04:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DentCorpApp', '0002_user_roles_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='roles',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='roles',
            name='id',
        ),
        migrations.AddField(
            model_name='roles',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default='------', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ape_usu',
            field=models.CharField(default='------', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dni_usu',
            field=models.CharField(default='------', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dom_usu',
            field=models.CharField(default='Direccion 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_alta_usu',
            field=models.DateField(default='------'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_baja_usu',
            field=models.DateField(default='------'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_ciu',
            field=models.ForeignKey(default='------', on_delete=django.db.models.deletion.CASCADE, to='DentCorpApp.ciudades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nom_usu',
            field=models.CharField(default='------', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel_usu',
            field=models.CharField(default='99999999', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolxusuario',
            name='id_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='DentCorpApp_users_roles', through='DentCorpApp.RolXUsuario', to='DentCorpApp.roles'),
        ),
    ]
