# Generated by Django 4.2.7 on 2023-11-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DentCorpApp', '0002_alter_planxcobertura_id_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorios',
            options={'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterField(
            model_name='especxusuario',
            name='id_rol_usu',
            field=models.ForeignKey(db_column='id_rol_usu', on_delete=django.db.models.deletion.PROTECT, related_name='especialidad_usuario', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='planxcobertura',
            name='id_cob',
            field=models.ForeignKey(db_column='id_cob', on_delete=django.db.models.deletion.PROTECT, to='DentCorpApp.coberturas'),
        ),
    ]
