# Generated by Django 4.2.7 on 2023-11-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0003_alter_consultorios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorios',
            options={'verbose_name_plural': 'Consultorios'},
        ),
    ]
