# Generated by Django 4.2.7 on 2023-11-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0004_alter_consultorios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name_plural': 'Especialidades'},
        ),
    ]
