# Generated by Django 4.2.7 on 2023-11-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0005_alter_especialidades_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajas',
            options={'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='coberturas',
            options={'verbose_name_plural': 'Coberturas'},
        ),
        migrations.AlterModelOptions(
            name='facturasservext',
            options={'verbose_name_plural': 'Facturas serv ext'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='planxcobertura',
            options={'verbose_name_plural': 'Planes x Coberturas'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='serviciosodontologicos',
            options={'verbose_name_plural': 'Servicios Odontológicos'},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name_plural': 'Turnos'},
        ),
    ]
