# Generated by Django 4.2.7 on 2023-11-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentCorpApp', '0006_alter_cajas_options_alter_ciudades_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturasodontologicas',
            options={'verbose_name_plural': 'Facturas Odontológicas'},
        ),
    ]
